### ISSUE TITLE
Blank screen after running `npm start`

### ISSUE THREAD

**Issue by Alir3z4** [AmirSavand/electro-music#1]
I'm on Windows 10, running latest from master branch

![image](https://user-images.githubusercontent.com/591113/41508656-dc9640cc-7250-11e8-88d2-286f68346e51.png)

**Comment by AmirSavand** [comment]
Currently all music is gathered from your music folder and this could mean there's no music at all.

Press CTRL + R to refresh and press CTRL + SHIFT + I to see console and errors.

**Comment by AmirSavand** [comment]
Press `CTRL + R` to fix for now.
